[[plugins]]
package = "@netlify/plugin-sitemap"

[plugins.inputs]
  buildDir = "public"
  filePath = "sitemap/sitemap.xml"
  # disable pretty URLS and keep `index.html` & trailing `.html` file references in paths
  prettyURLs = false